protected/models/Advert.php
<?php

class Advert extends CActiveRecord {
	
	const TYPE_NONE = 0;
	const TYPE_LEAFLETING = 1;
	const TYPE_PRESENTATION=2;
	const TYPE_BOTH = 3;
    
    public $username;
	public $activities = array();

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }
    
    public function tableName() {
        return '{{advert}}';
    }
    
	public function getClassName() {
		return 'Рекламный отчёт';
	}
    
    public function relations() {
        return array(
            'documents' => array(self::HAS_MANY,'AdvertDocument','advert_id'),
            'user' => array(self::BELONGS_TO,'UserMain','user_id'),
        );
    }
    
    public function rules() {
        return array(
            array('title', 'required'),
            array('title', 'length', 'max' => 255),
            array('description', 'length', 'max' => 2000),
            array('member_count', 'numerical', 'integerOnly' => true, 'min' => 0),
            array('activity_type', 'in', 'range' => array(self::TYPE_NONE, self::TYPE_LEAFLETING, self::TYPE_PRESENTATION, self::TYPE_BOTH)),
            array('date', 'date', 'format' => 'yyyy-MM-dd', 'on' => 'ajaxUpdate'),
            array('date', 'DateValidator', 'format' => 'd MMM yyyy', 'outputFormat' => 'yyyy-MM-dd', 'except' => 'ajaxUpdate'),
            array('documents', 'file', 'types' => 'jpg,jpeg,gif,png', 'maxFiles' => 100, 'maxSize' => 10 * 1024 * 1024, 'allowEmpty' => true),
			array('activities','safe'),
            array('title,member_count,activity_type,date,username', 'safe', 'on'=>'search'),
        );
    }
    
    public function behaviors() {
        return array(
            'formatDates' => array('class' => 'application.components.FormatDatesBehavior', 'attributes' => 'date'),
			'softDelete' => array('class' => 'application.components.SoftDeleteBehavior'),
        );
    }
    
    public function attributeLabels() {
        return array(
            'id' => 'Рекламный отчёт',
            'title' => 'Название',
            'description' => 'Описание',
            'member_count' => 'Кол-во участников',
            'activity_type' => 'Тип мероприятия',
            'activities' => 'Тип мероприятия',
            'date' => 'Дата проведения',
            'documents' => 'Фотографии',
            'user_id' => 'Администратор',
            'username' => 'Администратор',
            'create_date' => 'Дата создания',
            'update_date' => 'Дата обновления',
        );
    }
    
	public function defaultScope() {
		return array(
			'condition' => Yii::app()->user->getProjectIdCondition('project_id',$this->getTableAlias(false,false)),	
		);
	}

    public function search() {
        $criteria = new CDbCriteria;
        $criteria->compare('title',$this->title,true);
		if ($this->activities) $this->activity_type = array($this->activities,self::TYPE_BOTH);
		$criteria->compare('activity_type',$this->activity_type);
        $criteria->compare('member_count',$this->member_count);
        $criteria->compare('user_id',$this->user_id);
        if ($this->date) {
            $criteria->compare('date',Yii::app()->dateFormatter->format('yyyy-MM-dd',$this->date));
        }
        if ($this->username) {
            $criteria->compare('user.fullname',$this->username,true);
            $criteria->with = array('user');
        }
        return new CActiveDataProvider(__CLASS__, array('criteria' => $criteria, 'pagination' => array('pageSize' => 40)));
    }
    
    protected function afterConstruct() {
        $this->user_id = Yii::app()->user->id;
        parent::afterConstruct();
    }
	
	protected function afterFind() {
		switch ($this->activity_type) {
			case self::TYPE_LEAFLETING:
			case self::TYPE_PRESENTATION:
				$this->activities = array($this->activity_type);
				break;
			case self::TYPE_BOTH:
				$this->activities = array(self::TYPE_LEAFLETING,self::TYPE_PRESENTATION);
				break;
		}
		return parent::afterFind();
	}
	
	protected function beforeValidate() {
		if (parent::beforeValidate()) {
			if (!is_array($this->activities)) return false;
			$this->activity_type = count($this->activities) == 1 ? $this->activities[0] : (count($this->activities) == 2 ? self::TYPE_BOTH : self::TYPE_NONE);
			return true;
		}
	}
    
    protected function beforeSave() {
        if (parent::beforeSave()) {
            $this->update_date = time();
            if ($this->isNewRecord) {
                $this->create_date = $this->update_date;
                $this->project_id = Yii::app()->user->projectId;
                $this->user_id = Yii::app()->user->id;
            }
        }
        return true;
    }
    
    public function getActivityType($htmlStyle = false) {
		$labels = array(
			self::TYPE_LEAFLETING => 'Раздача листовок',
			self::TYPE_PRESENTATION=>'Презентация',
		);
		if (!$htmlStyle) return $labels;
		foreach ($labels as $currKey => $currLabel) if (!in_array($currKey,$this->activities)) unset($labels[$currKey]);
		return implode('<br>',$labels);
    }
	
	public function getName() { return $this->title; }
}

?>

protected/controllers/PaymentController.php
<?php

class PaymentController extends Controller {

	public $layout='//layouts/column2';
	public $modelName = 'PaymentTarif';

	public function actions() {
		return array(
			'ajaxUpdate' => array(
				'class' => 'application.controllers.actions.AjaxUpdateAction',
				'accessKey' => 'payment/update',
			),
		);
	}

	public function actionDelete($id) {
		$id = (int)$id;
		if (!Yii::app()->user->checkAccess('trcenter/delete')) throw new CHttpException(403);
		$model = $this->loadModel($id);
		$model->delete();
		if (Yii::app()->request->isAjaxRequest) {
			$this->logAction();
		} else {
			$this->redirect(array('index'));
		}
		Yii::app()->end();
	}

	public function actionUpdate($id) {
		$id = (int)$id;
		if (!Yii::app()->user->checkAccess('trcenter/update')) throw new CHttpException(403);
		$this->layout = '//layouts/column1';
		$model = TrCenter::model()->findByPk($id);
		if(!$model) throw new CHttpException(404);

		$payments = PaymentTarif::model()->findAll(array('condition'=>'tr_center_id='.$model->id));
		$payment = new PaymentTarif();

		if (isset($_POST['PaymentTarif'])) {
			$payment->attributes = $_POST['PaymentTarif'];
			if ($payment->save()) {
				$this->redirect(array('update','id'=>$model->id));
			}
		}

		$payment_search = new PaymentTarif('search');
		$payment_search->unsetAttributes();
		if (isset($_GET['PaymentTarif'])) $payment_search->attributes = $_GET['PaymentTarif'];
		$payment_search->tr_center_id=$model->id;

		$this->render('update', array('model' => $model, 'payments' => $payments, 'payment' => $payment, 'payment_search'=>$payment_search));
	}

}

?>

protected/views/payment/update.php
<?php
	$this->menu = array(
	    array('label'=>'Список учебных центров', 'url'=>array('trcenter/index')),
	    array('label'=>'Профиль учебного центра', 'url'=>array('trcenter/view', 'id' => $model->id)),
	);

	$this->breadcrumbs=array(
		'Список учебных центров'=>array('trcenter/index'),
	);
?>

<h2>Заработная плата преподавателям учебного центра <?=$model->name;?></h2>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'client-grid',
	'template'=>'<div class="pagerControl">{summary}{pager}</div>{items}',
	'dataProvider'=>$payment_search->search(),
	'filter' => $payment_search,
	'columns'=>array(
		'count_begin' => array(
           'class' => 'editable.EditableColumn',
           'name' => 'count_begin',
		   'editable' => array(
				'type' => 'text',
				'url' => $this->createUrl('ajaxUpdate'),
		   ),
        ),
		'if' => array(
           'class' => 'editable.EditableColumn',
           'name' => 'if',
		   'value' => 'PaymentTarif::$if_value[$data->if]',
		   'editable' => array(
				'type' => 'select',
				'url' => $this->createUrl('ajaxUpdate'),
			    'source' => PaymentTarif::$if_value
		   ),
        ),
		'summa' => array(
           'class' => 'editable.EditableColumn',
           'name' => 'summa',
		   'editable' => array(
				'type' => 'text',
				'url' => $this->createUrl('ajaxUpdate'),
		   ),
        ),
		array(
			'class'=>'ButtonColumn',
			'template' => '{delete}',
		),
	),
)); ?>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'trcenter-payment-form',
	'enableAjaxValidation'=>false,
)); ?>

    <?php echo $form->errorSummary($model); ?>

	<fieldset style="margin-right: 10px">
		<legend>Добавить тариф</legend>

		<div class="row">
			<div class="span-4">
				<?php echo $form->label($payment,'if'); ?>
				<?php echo $form->dropDownList($payment, 'if', PaymentTarif::$if_value, array('style'=>'width: 95%')); ?>
			</div>
			<div class="span-5">
				<?php echo $form->label($payment,'count_begin'); ?>
				<?php echo $form->textField($payment, 'count_begin', array('style'=>'width: 95%')); ?>
			</div>
			<div class="span-3">
				<?php echo $form->label($payment,'summa'); ?>
				<?php echo $form->textField($payment, 'summa', array('style'=>'width: 95%')); ?>
			</div>

			<?php echo $form->hiddenField($payment, 'tr_center_id', array('value'=>$model->id)); ?>
		</div>
	</fieldset>

	<div style="clear: left;"></div>

    <div class="row submit">
        <?php echo CHtml::submitButton($payment->isNewRecord ? 'Создать' : 'Сохранить',array('class' => 'btn btn-primary')); ?>
    </div>

<?php $this->endWidget(); ?>
</div><!-- form -->