8761349813058edu-dev.gaikagroup.com/protected/models/Schedule.php
<?php

class Schedule extends CActiveRecord {
	
	const CONDUCT_UNDEFINED = 0;
	const CONDUCT_OK		= 1;
	const CONDUCT_MOVED	 	= 2;
	const CONDUCT_CANCELED  = 3;

    public $hours_start;
    public $minutes_start;

    public $hours_end;
    public $minutes_end;

	public $date;
	public $datefrom;
	public $dateto;
	
	public $teacher_name;
	public $course_name;
	public $group_name;
	public $city_id;

	protected $_currentDatetimeStart = 0;
	protected $_academicHours;

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }
    
    public function tableName() {
        return '{{schedule}}';
    }
	
	public function getClassName() {
		return 'Урок';
	}
    
    public function rules() {
        return array(
            array('hours_start, minutes_start, hours_end, minutes_end, datetime_start, datetime_end, tr_center_id, tr_group_id, tr_course_id, project_id', 'required', 'on' => 'create, update'),
			array('hours_start, hours_end', 'numerical', 'integerOnly' => false, 'min' => 0, 'max' => 23, 'on' => 'create, update'),
			array('minutes_start, minutes_end', 'numerical', 'integerOnly' => false, 'min' => 0, 'max' => 59, 'on' => 'create, update'),
			array('day', 'numerical', 'min' => 0, 'max' => 7),
			array('date, datefrom, dateto', 'date', 'format' => 'd MMM yyyy', 'on' => 'create, update, search'),

            array('datetime_start', 'date', 'format' => 'd MMM yyyy HH:mm:00', 'timestampAttribute' => 'datetime_start', 'allowEmpty' => true, 'on' => 'create, update, search'),
            array('datetime_end', 'date', 'format' => 'd MMM yyyy HH:mm:00', 'timestampAttribute' => 'datetime_end', 'allowEmpty' => true, 'on' => 'create, update, search'),
            array('hours_start, minutes_start, hours_end, minutes_end, datetime_start, datetime_end, tr_center_id, tr_group_id, tr_course_id, date, datefrom, dateto, city_id', 'safe', 'on' => 'search'),
			
			array('datetime_start', 'date', 'format' => 'yyyy-MM-dd HH:mm', 'timestampAttribute' => 'datetime_start', 'on' => 'description, description_conducted, description_clients, description_conducted_clients'),
			array('datetime_end', 	'date', 'format' => 'yyyy-MM-dd HH:mm', 'timestampAttribute' => 'datetime_end',   'on' => 'description, description_conducted, description_clients, description_conducted_clients'),
			array('description', 'length', 'max'=>2000, 'on'=>'description, description_conducted, description_clients, description_conducted_clients'),
			array('is_conducted', 'in', 'range' => array(self::CONDUCT_UNDEFINED, self::CONDUCT_OK, self::CONDUCT_MOVED, self::CONDUCT_CANCELED), 'on' => 'conducted, description_clients, description_conducted, conducted_clients, description_conducted_clients'),
			array('group_name, teacher_name, tr_center_id, course_name, datetime_start, is_conducted', 'safe', 'on' => 'list'),

            array('datetime_start', 'compare', 'compareAttribute' => 'datetime_end', 'operator' => '<', 'message'=>'Дата начала должна быть меньше даты завершения'),
            array('datetime_end', 'compare', 'compareAttribute' => 'datetime_start', 'operator' => '>', 'message'=>'Дата завершения должна быть больше даты начала'),
        );
    }

    public function behaviors() {
        return array(
            'formatDates' => array('class' => 'application.components.FormatDatesBehavior', 'attributes' => array()),
			'softDelete' => array('class' => 'application.components.SoftDeleteBehavior', 'parents' => array('group')),
        );
    }
    
    public function relations() {
        return array(
            'user' => array(self::BELONGS_TO, 'UserMain', 'user_id'),
            'group' => array(self::BELONGS_TO, 'TrGroup', 'tr_group_id'),
            'center' => array(self::BELONGS_TO, 'TrCenter', 'tr_center_id'),
            'course' => array(self::BELONGS_TO, 'TrCourse', 'tr_course_id'),
			'clients' => array(self::HAS_MANY, 'TrClientLog', 'tr_lesson_id'),
			'summaryDebt' => array(self::STAT, 'TrClientLog', 'tr_lesson_id', 'select' => 'SUM(debt)'),
			'seenNoted' => array(self::STAT, 'TrClientLog', 'tr_lesson_id', 'select' => 'SUM(is_skipped)'),
        );
    }
    
    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'tr_center_id' => 'Учебный центр',
            'tr_group_id' => 'Группа',
			'group_name' => 'Группа',
            'tr_course_id' => 'Предмет',
			'course_name' => 'Предмет',
			'day' => 'Дни',
			'time_start' => 'Время начала',
			'time_end' => 'Время завершения',
			'datetime_start' => 'Дата начала',
			'datetime_end' => 'Дата завершения',
			'date' => 'Дата',
			'minutes' => 'Минуты',
			'user_id' => 'Пользователь',
			'create_date' => 'Дата создания',
			'update_date' => 'Дата обновления',
			'description' => 'Описание',
			'is_conducted' => 'Статус',
			'teacher_name' => 'Преподаватель',
        );
    }
	
	public function defaultScope() {
		return array(
			'condition' => Yii::app()->user->getProjectIdCondition('project_id',$this->getTableAlias(false,false)),	
		);
	}
	
	public function scopes() {
		$currDatetime = time();
		return array(
			'future' => array('condition' => 'datetime_start > '.$currDatetime, 'order' => 'datetime_start ASC'),
			'past'	 => array('condition' => 'datetime_start <= '.$currDatetime, 'order' => 'datetime_start DESC'),
		);
	}
	
	protected function afterFind() {
		if ($this->hasAttribute('datetime_start')) $this->_currentDatetimeStart = $this->datetime_start;
		
        $this->datesFormatFromTo('d MMM yyyy', 'datetime_start', 'date');
        $this->datesFormatFromTo('d MMM yyyy', 'datetime_start', 'datefrom');
        $this->datesFormatFromTo('d MMM yyyy', 'datetime_end', 'dateto');
        $this->datesFormatFromTo('HH', 'datetime_start', 'hours_start');
        $this->datesFormatFromTo('mm', 'datetime_start', 'minutes_start');
        $this->datesFormatFromTo('HH', 'datetime_end', 'hours_end');
        $this->datesFormatFromTo('mm', 'datetime_end', 'minutes_end');
			
		if ($this->scenario != 'search' && $this->_currentDatetimeStart <= time() && !count($this->clients) && $this->group && $this->group->members) {
			foreach ($this->group->members as $currentClient) {
				$client = new TrClientLog;
				$client->tr_group_id = $this->tr_group_id;
				$client->client_id = $currentClient->id;
				$client->is_skipped = TrClientLog::SKIPPED_UNDEFINED;
				$client->tr_lesson_id = $this->id;
				$client->insert();
			}
		}
		parent::afterFind();
	}
	
	protected function beforeDelete() {
		if (parent::beforeDelete()) {
			if ($this->clients) {
				foreach ($this->clients as $currentClient) $currentClient->delete();
			}
			return true;
		}
	}
	
    protected function beforeSave() {
        if (!parent::beforeSave()) return false;
        if ($this->isNewRecord) {
            $this->create_date = time();
            $this->update_date = $this->create_date;
			$this->user_id = Yii::app()->user->id;
			if (!$this->group) {
                $this->addError('badGroup', "Такой группы не существует" );
                return false;
            }
			$rateObj = CourseRates::model()->findByAttributes(array('teacher_id' => $this->group->teacher_id, 'group_id' => $this->group->id));
			if ($rateObj) $this->teacher_rate = $rateObj->rate;
        } else {
            $this->update_date = time();
        }
        return true;
    }
	
	protected function afterSave() {
		if ($this->is_conducted == self::CONDUCT_MOVED || $this->is_conducted == self::CONDUCT_CANCELED) {
			foreach ($this->clients as $currentClient) {
				$currentClient->is_skipped = TrClientLog::SKIPPED_BY_REASON;
				$currentClient->save();
			}
		}
		parent::afterSave();
	}
	
	protected function afterConstruct() {
		$this->description = '';
		$this->is_conducted = self::CONDUCT_UNDEFINED;
		parent::afterConstruct();
	}

    protected function beforeValidate() {
		
		if (parent::beforeValidate()) {
			if ($this->scenario == 'ajaxUpdate') $this->setUpdateScenario();
			if ($this->scenario == 'create' || $this->scenario == 'update' || $this->scenario == 'search') {
				$this->datetime_start = $this->date . " " . $this->hours_start . ":" . $this->minutes_start . ":00";
				$this->datetime_end = $this->date . " " . $this->hours_end . ":" . $this->minutes_end . ":00";
			}
			return true;
		}

    }
	
	public function search() {

		$criteria = new CDbCriteria;
		$criteria->compare('project_id',Yii::app()->user->projectIdCompare);
		$criteria->compare('tr_center_id',$this->tr_center_id);
		$criteria->compare('tr_group_id',$this->tr_group_id);
		$criteria->compare('tr_course_id',$this->tr_course_id);
		$criteria->compare('day',$this->day);

        if ($this->city_id) {
            $projects = UserMain::projectsByCityId($this->city_id);
            $criteria->addInCondition('project_id', $projects);
        }

        $datefrom = CDateTimeParser::parse($this->datefrom,'d MMM yyyy');
        $dateto = CDateTimeParser::parse($this->dateto,'d MMM yyyy') + 60*60*24;
        if ($datefrom && $dateto)
		    $criteria->addBetweenCondition('datetime_start', $datefrom, $dateto);

		$criteria->order = 'datetime_start ASC, id ASC';

		return Schedule::model()->findAll($criteria);

		//return new CActiveDataProvider('Schedule', array('criteria' => $criteria, 'pagination'=>false));
	
	}
	
	public function getDayList() {
		return array(
			'Понедельник',
			'Вторник',
			'Среда',
			'Четверг',
			'Пятница',
			'Суббота',
			'Воскресенье'
		);
	}
	
	public function getHourList() {
		$result = array();
		for ($i = 8; $i < 23; $i++) {
            $i = $i < 10 ? '0'.$i : $i;
			$result[$i] = $i;
		}
		return $result;
	}
	
	public function getMinuteList() {
		$result = array();
		for ($i = 0; $i < 60; $i+=5) {
            $i = $i < 10 ? '0'.$i : $i;
			$result[$i] = $i;
		}
		return $result;
	}
	
	public function getName() {
		$name = Yii::app()->dateFormatter->format('d MMM yyyy, HH:mm',$this->_currentDatetimeStart);
		if ($this->group) $name = $this->group->name . ', '.$name;

8761349813058edu-dev.gaikagroup.com/protected/views/schedule/_form.php
<?php
/* @var $form CActiveForm */
?>

<script type="text/javascript">

    $(function(){

        var ScheduleForm = {
            action: '<?php echo $this->action->id?>',
            controller: '<?php echo Yii::app()->baseUrl; ?>/schedule/',
            filtered: <?php echo (int)isset($_GET['Schedule']); ?>,
            form: $("#schedule-form"),
            center: $("#Schedule_tr_center_id"),
            group: $('#Schedule_tr_group_id'),
            course: $('#Schedule_tr_course_id'),

            groupListUpdate: function() {
                var ids = [];
                var $this = this;

                this.group.find(':selected, :checked').each(function(){
                    ids.push($(this).attr('value'));
                });

                this.group.load(this.controller + 'getGroups?' + this.form.serialize(), function(){
//                    $this.group.find('[value]').each(function(){
//                        //console.log(ids);
//                        //console.log($(this).attr('value'));
//                        if ($.inArray($(this).attr('value'), ids))
//                            $(this).attr('checked','checked').attr('selected','selected');
//                    });
                });

            },
            courseListUpdate: function() {
                var ids = [];
                var $this = this;

                this.group.find(':selected, :checked').each(function(){
                    ids.push($(this).attr('value'));
                });

                this.course.load(this.controller + 'getCourse?' + this.form.serialize(), function(){
//                    $this.group.find('[value]').each(function(){
//                        //console.log(ids);
//                        //console.log($(this).attr('value'));
//                        if ($.inArray($(this).attr('value'), ids))
//                            $(this).attr('checked','checked').attr('selected','selected');
//                    });
                });
            },
            reStyle: function() {
                this.form.find('.span-5').addClass('labelinline').find('label:first').hide().after('<br>');
                this.form.find('label[for=Schedule_tr_center_id]').show();
                this.form.find('.span-5 > span').addClass('noBold');
                if (this.filtered)
                    this.form.find('label').show();
            },
            init: function() {

                if (this.action == 'index') {
                    this.reStyle();
                }

                var $this = this;
                this.center.change(function(){
                    $this.form.find('label').show();
                    $this.groupListUpdate();
                    $this.courseListUpdate();
                });

            }
        };

        ScheduleForm.init();
    });

</script>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'schedule-form',
	'action'=>Yii::app()->baseUrl.'/schedule/'.(isset($_GET['frame']) ? 'frame-'.$_GET['project_id'] : $this->action->id . '/' . $model->id),
    'method'=> $this->action->id == 'index' ? 'get' : 'post',
	'enableAjaxValidation'=>false,
)); ?>
 
    <?php echo $form->errorSummary($model); ?>

    <div class="row">

        <?php if (Yii::app()->user->checkAccess('owner')) { ?>
            <div class="cityList">
                <?php echo $form->dropDownList($model, 'city_id', City::listArray(),array('empty' => 'Все города'));?>
            </div>
        <?php } ?>

        <div class="span-<?php echo isset($_GET['frame'])?'8':'11'?>">
            <?php if ($this->action->id != 'index') { ?>
                <div class="row">
                    <div class="span-5 first  labelinline">
                        <?php echo $form->label($model,'time_start'); ?><br>
                        <?php echo $form->dropDownList($model, 'hours_start', $model->hourList); ?>
                        <?php echo $form->dropDownList($model, 'minutes_start', $model->minuteList); ?>
                    </div>
                    <div class="span-6 last labelinline">
                        <?php echo $form->label($model,'time_end'); ?><br>
                        <?php echo $form->dropDownList($model, 'hours_end', $model->hourList); ?>
                        <?php echo $form->dropDownList($model, 'minutes_end', $model->minuteList); ?>
                    </div>
                </div>
            <?php } ?>
            <div class="clear"></div>

            <div class="row">
                <div class="span-5">
                    <?php echo $form->label($model,'tr_center_id'); ?>
                    <?php
                        if ($this->action->id == 'index') {
                            echo $form->checkBoxList($model, 'tr_center_id', TrCenter::model()->getCenterNames(Yii::app()->user->projectIdCompare));
                        } else {
                            if (($groupId = Yii::app()->request->getParam('id', false)) && ($trGroup = TrGroup::model()->findByPk($groupId)))
                                $listCenter = array($trGroup->tr_center_id => $trGroup->center->name);
                            else
                                $listCenter = false;
                            echo $form->dropDownList($model, 'tr_center_id', $listCenter ? $listCenter : TrCenter::model()->centerNames, array('empty'=>$listCenter?null:'Выберите центр'));
                        }
                    ?>
                </div>
                <div class="span-5">
                    <?php echo $form->label($model,'tr_group_id'); ?>
                    <?php
                        if ($this->action->id == 'index') {
                            $listGroup = isset($_GET['Schedule']['tr_center_id']) ? CHtml::listData(TrGroup::getByCenterId($_GET['Schedule']['tr_center_id']), 'id', 'name') : array();
                            echo $form->checkBoxList($model, 'tr_group_id', $listGroup);
                        } else {
                            $listGroup = $model->tr_center_id ? CHtml::listData(TrGroup::getByCenterId($model->tr_center_id), 'id', 'name') : array();
                            
                            if (($groupId = Yii::app()->request->getParam('id', false)) && ($trGroup = TrGroup::model()->findByPk($groupId)))
                                $listGroup = array($groupId => $trGroup->name);
                            
                            echo $form->dropDownList($model, 'tr_group_id', $listGroup, array('empty' => $groupId ? null : '--'));
                        }
                    ?>
                </div>
            </div>

            <div class="clear"></div>

            <div class="row">
                <div class="span-5">
                    <?php echo $form->label($model,'tr_course_id'); ?>
                    <?php
                    if ($this->action->id == 'index') {
                        $listData = isset($_GET['Schedule']['tr_center_id']) ? CHtml::listData(TrCourse::findAllByCenter($_GET['Schedule']['tr_center_id']), 'id', 'name') : array();
                        echo $form->checkBoxList($model, 'tr_course_id', $listData);
                    } else {
                        echo $form->dropDownList($model, 'tr_course_id', TrCourse::listArray(), array('empty'=>'--'));
                    }
                    ?>
                </div>
            </div>
            <div class="clear"></div>

        </div>
        <div class="span-<?php echo isset($_GET['frame'])?'8':'11'?>">
            <?php
                $btnText = '';
                switch ($this->action->id) {
                    case 'create':
                        $btnText = 'Добавить';
                        $tabs = array();
                        $tabs['Период'] = $this->renderPartial('_form_period',array('model' => $model,'form' => $form),true);
                        $tabs['Дата'] = $this->renderPartial('_form_date',array('model' => $model,'form' => $form),true);
                        $this->widget('zii.widgets.jui.CJuiTabs', array(
                            'tabs'=>$tabs,
                            'options'=>array(
                                'collapsible'=>false,
                                'selected'=>0,
                            ),
                            'htmlOptions'=>array(
                                'style'=>'width:100%;'
                            ),
                        ));
                        break;
                    case 'update':
                        $btnText = 'Сохранить';
                        $this->renderPartial('_form_period',array('model' => $model,'form' => $form));
                        break;
                    case 'index':
                        $btnText = 'Показать';
                        $this->renderPartial('_form_period',array('model' => $model,'form' => $form));
                        break;
                }

            ?>
        </div>
    </div>
    <div class="clear"></div>
    <div class="row submit" style="margin-top: 40px">
        <?php echo CHtml::submitButton($btnText, array('class'=>'btn btn-primary btn-small')); ?>
    </div>

    <div class="clear"></div>
 
<?php $this->endWidget(); ?>
</div><!-- form -->

8761349813058edu-dev.gaikagroup.com/protected/views/schedule/_form_date.php
<?php
    $datePickerOptions = array(
        'dateFormat' => 'd M yy',
        'changeYear' => true,
    );

?>
<div class="row">
    <div class="span-5"><label for="datefrom">Дата</label>
        <?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
            'model' => $model,
            'attribute' => 'date',
            'options' => $datePickerOptions,
            'htmlOptions' => array('size' => 15),
        ));
        ?>
    </div>
</div>

<div class="clear"></div>

8761349813058edu-dev.gaikagroup.com/protected/views/schedule/_form_period.php
<?php
    $datePickerOptions = array(
        'dateFormat' => 'd M yy',
        'changeYear' => true,
    );

?>
<div class="row">
    <div class="span-4 first">
        <div class="row">
            <div class="span-4"><label for="datefrom">Период, с</label>
                <?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'model' => $model,
                    'attribute' => 'datefrom',
                    'options' => $datePickerOptions,
                    'htmlOptions' => array('size' => 15),
                ));
                ?>
            </div>
        </div>

        <div class="clear"></div>

        <div class="row">
            <div class="span-4"><label for="dateto">по</label>
                <?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'model' => $model,
                    'attribute' => 'dateto',
                    'options' => $datePickerOptions,
                    'htmlOptions' => array('size' => 15),
                ));?>
            </div>
        </div>

        <div class="clear"></div>
    </div>
    <?php if ($this->action->id != 'index') { ?>
        <div class="span-4 last">
            <div class="row labelinline span-4">

                <?php echo $form->label($model,'day'); ?><br>
                <?php echo $form->checkboxList($model, 'day', $model->dayList, array('separator'=>' <br>', 'labelOptions'=>array('class'=>'noBold'))); ?>
            </div>

            <div class="clear"></div>
        </div>
    <?php } ?>
</div>

<div class="clear"></div>

8761349813058edu-dev.gaikagroup.com/protected/views/schedule/_list_future.php
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'trlesson-predictions-grid',
    'template'=>'<div class="pagerControl">{summary}{pager}</div>{items}',
	'dataProvider'=>$model->future()->dataProvider,
	'filter' => $model,
	'afterAjaxUpdate' => 'function(){
		jQuery("#datetime_future").datepicker({
			dateFormat: "d M yy",
			monthNames: '.CJSON::encode(array('Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь')).',
			monthNamesShort: '.CJSON::encode(array('янв','февр','марта','апр','мая','июня','июля','авг','сент','окт','нояб','дек')).',
			dayNames: '.CJSON::encode(array('Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота')).',
            dayNamesShort: '.CJSON::encode(array('Вс','Пн','Вт','Ср','Чт','Пт','Сб')).',
            dayNamesMin: '.CJSON::encode(array('Вс','Пн','Вт','Ср','Чт','Пт','Сб')).',
            firstDay: 1,
			changeYear: true
		});
	}',
	'columns'=>array(
		array(
			'name' => 'datetime_start',
			'header' => 'Занятие',
			'type' => 'raw',
			'value' => 'CHtml::link(Yii::app()->dateFormatter->format("dd MMM yyyy, HH:mm",$data->datetime_start),array("schedule/view", "id" => $data->id))',
			'filter' => $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                'model' => $model,
              	'id' => 'datetime_future',
                'attribute' => 'datetime_start',
                'options' => array(
                    'dateFormat' => 'd M yy',
                    'changeYear' => true
                ),
            ), true),
		),
		array(
			'name' => 'group_name',
			'type' => 'raw',
			'value'=> 'CHtml::link(CHtml::encode($data->group->name),array(\'trgroup/view\', \'id\' => $data->tr_group_id),array("target" => "_blank"))',
		),
		array(
			'name' => 'tr_center_id',
			'type' => 'raw',
			'value'=> 'CHtml::link($data->center->name,array("trcenter/view", "id" => $data->tr_center_id))',
			'filter' => CHtml::activeDropDownList($model,'tr_center_id',$model->centerList,array('empty' => 'Все')),
		),
		array(
			'name' => 'course_name',
			'type' => 'raw',
			'value'=> 'CHtml::link($data->course->name,array("trcourse/view", "id" => $data->tr_course_id))',
		),
		array(
			'name' => 'teacher_name',
			'type' => 'raw',
			'value'=> '$data->group->teacher ? $data->group->teacher->profileLink : ""',
		),
		array(
			'class' => 'ButtonColumn',
			'template' => '{delete}',
		),
	),
)); ?>

8761349813058edu-dev.gaikagroup.com/protected/views/schedule/_list_past.php
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'trlesson-grid',
    'template'=>'<div class="pagerControl">{summary}{pager}</div>{items}',
	'dataProvider'=>$model->past()->dataProvider,
	'filter' => $model,
	'afterAjaxUpdate' => 'function(){
		jQuery("#datetime_past").datepicker({
			dateFormat: "d M yy",
			monthNames: '.CJSON::encode(array('Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь')).',
			monthNamesShort: '.CJSON::encode(array('янв','февр','марта','апр','мая','июня','июля','авг','сент','окт','нояб','дек')).',
			dayNames: '.CJSON::encode(array('Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота')).',
            dayNamesShort: '.CJSON::encode(array('Вс','Пн','Вт','Ср','Чт','Пт','Сб')).',
            dayNamesMin: '.CJSON::encode(array('Вс','Пн','Вт','Ср','Чт','Пт','Сб')).',
            firstDay: 1,
			changeYear: true
		});
	}',
	'columns'=>array(
		array(
			'name' => 'datetime_start',
			'header'=>'Занятие',
			'type' => 'raw',
			'value' => 'CHtml::link(Yii::app()->dateFormatter->format("dd MMM yyyy, HH:mm",$data->datetime_start),array("schedule/view", "id" => $data->id))',
			'filter' => $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                'model' => $model,
              	'id' => 'datetime_past',
                'attribute' => 'datetime_start',
                'options' => array(
                    'dateFormat' => 'd M yy',
                    'changeYear' => true
                ),
            ), true),
		),
		array(
			'name' => 'group_name',
			'type' => 'raw',
			'value'=> 'CHtml::link(CHtml::encode($data->group->name),array(\'trgroup/view\', \'id\' => $data->tr_group_id),array("target" => "_blank"))',
		),
		array(
			'name' => 'tr_center_id',
			'type' => 'raw',
			'value'=> 'CHtml::link($data->center->name,array("trcenter/view", "id" => $data->tr_center_id))',
			'filter' => CHtml::activeDropDownList($model,'tr_center_id',$model->centerList,array('empty' => 'Все')),
		),
		array(
			'name' => 'course_name',
			'type' => 'raw',
			'value'=> 'CHtml::link($data->course->name,array("trcourse/view", "id" => $data->tr_course_id))',
		),
		array(
			'name' => 'teacher_name',
			'type' => 'raw',
			'value'=> '$data->group->teacher ? $data->group->teacher->profileLink : ""',
		),
		'is_conducted' => array(
			'name' => 'is_conducted',
			'type' => 'raw',
			'value' => '$data->conductedList[$data->is_conducted]',
			'filter' => CHtml::activeDropDownList($model,'is_conducted',$model->conductedList,array('empty' => 'Все')),
		),
		array(
			'class' => 'ButtonColumn',
			'template' => '{delete}',
		),
	),
)); ?>

8761349813058edu-dev.gaikagroup.com/protected/views/schedule/_tl_event.php
<?php

$pxLeft = floor((($schedule->hours_start - $dayStart) * 60 + $schedule->minutes_start) * 100/60); // 100 px in hour
$pxWidth = floor(( (($schedule->hours_end - $dayStart) * 60 + $schedule->minutes_end) - (($schedule->hours_start - $dayStart) * 60 + $schedule->minutes_start) ) * 100 / 60) - 3 ;
?>
<div
    data-show-description="true"
    class="tl_event <?= $schedule->seenNoted ? '' : 'tl_event_alert' ;?>" data-eventid="<?php echo $schedule->id ?>"
    data-event="<?php echo $schedule->id ?>"
    style="left: <?php echo $pxLeft ?>px; width: <?php echo $pxWidth ?>px;  "
    data-location="<?php echo $locationKey; ?>"
    >


    <span class="tl_event_time">
        <?php echo $schedule->hours_start ?>:<?php echo $schedule->minutes_start ?> - <?php echo $schedule->hours_end ?>:<?php echo $schedule->minutes_end ?>
    </span>

    <h2><?php echo $schedule->course->name; ?></h2>

    <p class="tl_subtitle">
        <?php echo $schedule->group ? $schedule->group->name : '-'; ?>
        <?php echo $schedule->center ? $schedule->center->name : '-'; ?>
    </p>

</div>

8761349813058edu-dev.gaikagroup.com/protected/views/schedule/create.php
<h1>Добавление расписания</h1>

<?php
    $this->renderPartial('_form',array('model'=>$model));
?>