protected/controllers/ClientController.php
<?php

	class ClientController extends Controller {

		public $modelName = 'Client';
		public $layout='//layouts/column1';

		public function actions() {
			return array(
				'ajaxUpdate' => array(
					'class' => 'application.controllers.actions.AjaxUpdateAction',
					'accessKey' => 'client/update',
				),
				'ajaxUpdateRequest' => array(
					'class' => 'application.controllers.actions.AjaxUpdateAction',
					'modelName' => 'ClientRequest',
					'accessKey' => 'client/update',
				),
				'ajaxUpdateBalance' => array(
					'class' => 'application.controllers.actions.AjaxUpdateAction',
					'modelName' => 'TrIncome',
					'accessKey' => 'client/finance',
				),
			);
		}

		public function actionRequestList() {
			if (!Yii::app()->user->checkAccess('client/index')) throw new CHttpException(403);
			$criteria = new CDbCriteria;
			$criteria->select = 'id, fullname, email, phone_num, datetime, school, social_vk, other, status, source, project_id';
			$dataProvider = new CActiveDataProvider('ClientRequest', array(
				'criteria' => $criteria,
				'pagination' => array('pageSize' => 40),
				'sort' => array('defaultOrder' => 'datetime ASC'),
			));
			// if (Yii::app()->user->model->project_id) $criteria->compare('project_id',Yii::app()->user->model->project_id);
			if (Yii::app()->request->isAjaxRequest) {
				$this->renderPartial('_index_requests', array('dataProvider' => $dataProvider),false,true);
			} else {
				$this->render('_index_requests', array('dataProvider' => $dataProvider));
			}
		}

		public function actionDebtList() {
			if (!Yii::app()->user->checkAccess('client/debt')) throw new CHttpException(403);

			$filter = new DebtFilterForm;
			$filterData = Yii::app()->request->getPost(get_class($filter));
			if ($filterData) {
				$filter->attributes = $filterData;
				if (!$filter->validate()) throw new CHttpException(400);
				$update = $filter->update;
			}

			$result = array();
			$criteria = new CDbCriteria;
			$criteria->order = 'groups.tr_center_id ASC';

			$criteria->compare('t.project_id',$filter->partners);
			$withArr = array(
				'joinType' => 'INNER JOIN',
			);
			if ($filter->centers || $filter->groups) {
				$conditions = array();
				if ($filter->centers) array_push($conditions,'groups.tr_center_id IN ('.implode(', ',$filter->centers).')');
				if ($filter->groups) array_push($conditions,'groups.id IN ('.implode(', ',$filter->groups).')');
				$withArr['condition'] = implode(' AND ',$conditions);
			}
			$criteria->with = array('groups' => $withArr);

			foreach (Client::model()->findAll($criteria) as $currClient) {
				foreach ($currClient->groups as $currGroup) {
					if ($currClient->balanceRel > 0)
						continue;

					if ($currGroup->getDebtByClientId($currClient->id)) {
						array_push($result, clone $currClient->attachGroup($currGroup));
						$filter->addBasePartner($currClient->partner);
						$filter->addBaseCenter($currClient->attachedGroup->center,$currClient->partner->id);
						$filter->addBaseGroup($currClient->attachedGroup,$currClient->attachedGroup->tr_center_id);
					}
				}
			}

			if (Yii::app()->request->isAjaxRequest) {
				if (!$filterData) {
					$this->renderPartial('_index_debts', array(
						'dataProvider' => new CArrayDataProvider($result, array('pagination' => array('pageSize' => 40))),
						'selector' => $filter,
					),false,true);
				} else {
					echo CJSON::encode(array(
						'grid' => $this->renderPartial('_index_debts_grid', array(
							'dataProvider' => new CArrayDataProvider($result, array('pagination' => array('pageSize' => 40))),
						),true,true),
						'groups' => $filter->centers ? $this->renderPartial('_index_debts_groupfilter', array(
							'selector' => $filter,
						),true,true) : '',
						'centers' => $filter->partners ? $this->renderPartial('_index_debts_centerfilter', array(
							'selector' => $filter,
						),true,true) : '',
						'refreshcenters' => $update == 'partner',
						'refreshgroups' => $update == 'center',
					));
				}
				Yii::app()->end();
			} else {
				$this->render('_index_debts', array(
					'dataProvider' => new CArrayDataProvider($result, array('pagination' => array('pageSize' => 40))),
					'selector' => $filter,
				));
			}
		}

		public function actionIndex() {
			if (!Yii::app()->user->checkAccess('client/index')) throw new CHttpException(403);
			$model = new Client('search');
			$model->unsetAttributes();
			if (isset($_GET['Client'])) $model->attributes = $_GET['Client'];
			if ($model->reg_date) $model->validate(array('reg_date'));
			$this->render('index', array('model' => $model, 'item' => Yii::app()->request->getParam('new') !== null ? 1 : 0));
		}

		public function actionView($id) {
			if (!Yii::app()->user->checkAccess('client/view')) throw new CHttpException(403);
			if (!($model = Client::model()->findByPk($id))) $this->redirect(array('client/index'));
			$comments = Yii::app()->user->checkAccess('client/update','addcomment') || Yii::app()->user->checkAccess('client/view','comment') ? new ClientComments('search') : null;
			if ($comments) {
				$comments->unsetAttributes();
				if (isset($_GET['ClientComments'])) {
					$comments->attributes = $_GET['ClientComments'];
				}
				$comments->client_id = $id;
			}
			$clientBalance = new TrIncome('clientUpdate');
			$clientBalance->client_id = $id;
			$this->render('view', array('model' => $model, 'comments' => $comments, 'clientBalance' => $clientBalance));
		}

		/*
		 * Request -> Client
		 */

		public function actionComplete($id) {
			if (!Yii::app()->user->checkAccess('client/update')) throw new CHttpException(403);

			if (!($request = ClientRequest::model()->findByPk($id))) throw new CHttpException(404, 'Указанная Вами заявка в системе не зарегистрирована!');

			// ClientRequest -> Client
			$model = $request->extend();
			$model->reg_date = time();
			$model->project_id = Yii::app()->user->projectId;

			if ($model->save()) {
				$request->hiddenDelete();
				$this->redirect(array('view','id'=>$model->id));
			}

			Yii::app()->user->setFlash('clientImportError', $model->getErrors());
			$this->redirect(array('client/new'));
		}

		public function actionReject($id) {
			if (!Yii::app()->user->checkAccess('client/delete')) throw new CHttpException(403);
			if (!($model = ClientRequest::model()->findByPk($id))) throw new CHttpException(404, 'Указанная Вами заявка в системе не зарегистрирована!');
			$model->delete();
			$this->logAction($model,'delete');
		}

		public function actionComment($id) {
			$id = (int)$id;
			if (!Yii::app()->user->checkAccess('client/update','addcomment')) throw new CHttpException(403);
			if (isset($_POST['ClientComments'])) {
				$commentsObj = new ClientComments;
				$commentsObj->attributes = $_POST['ClientComments'];
				$commentsObj->user_id = Yii::app()->user->id;
				$commentsObj->client_id = $id;
				$commentsObj->save();
				$this->storeModel($commentsObj);
			}
			if(!Yii::app()->request->isAjaxRequest)
				$this->redirect(array('view', 'id' => $id));
		}

		public function actionCommentDelete($id) {
			$id = (int)$id;
			if (!Yii::app()->user->checkAccess('client/update','addcomment')) throw new CHttpException(403);

			ClientComments::model()->deleteByPk($id);
		}

		public function actionCreate() {

			if (!Yii::app()->user->checkAccess('client/create')) throw new CHttpException(403);

			// установить права доступа #pdovlatov

			$managerList = UserMain::getManagerList();

			$model = new Client(($managerList && (Yii::app()->user->model->is_partner || Yii::app()->user->model->is_owner)) ? 'createWithManagers' : 'createDefault');

			if (isset($_POST['Client'])) {
				$model->attributes = $_POST['Client'];
				$model->reg_date = time();
				$model->project_id = Yii::app()->user->projectId;

				if ($model->save()) {
					$this->storeModel($model);
					$this->beforeRedirect();
					echo "<script>location.href='".$this->createUrl('client/view', array('id' => $model->id))."'</script>";
					Yii::app()->end();
				}
			}
			if (Yii::app()->request->isAjaxRequest) {
				$this->renderPartial('_form', array('model' => $model, 'managers' => $managerList), false, true);
			} else {
				$this->render('create', array('model' => $model, 'managers' => $managerList));
			}

		}

		public function actionDelete($id) {
			$id = (int)$id;
			if (!Yii::app()->user->checkAccess('client/delete')) throw new CHttpException(403);
			$model = $this->loadModel($id);
			$model->delete();
			$this->redirect(array('client/index'));
		}

		public function actionAjaxFinance($id) {
			$id = (int)$id;
			if (!Yii::app()->request->isAjaxRequest) $this->redirect(array('view', 'id' => $id));
			if (!Yii::app()->user->checkAccess('client/finance')) throw new CHttpException(403);
			$client = $this->loadModel($id);

			if(Yii::app()->request->isPostRequest) {
				$model = new TrIncome('clientInsert');
				$model->attributes = Yii::app()->request->getPost('TrIncome');
				$model->client_id = $id;
				if($model->save()) {
					$this->logAction($model,'balance');
					$newBalance = new TrIncome('clientInsert');
					$newBalance->client_id = $id;
					echo CJSON::encode(array('balance' => $client->getRelated('balanceRel',true)));
				} else {
					$errors = array_map(function($v){ return join(', ', $v); }, $model->getErrors());
					echo CJSON::encode(array('errors' => $errors));
				}
			} else {
				throw new CHttpException(400);
			}
		}

		public function actionSuggestName($term) {
			if (!Yii::app()->request->isAjaxRequest) throw new CHttpException(400);
			if (!Yii::app()->user->checkAccess('client/index')) throw new CHttpException(403);
			echo CActiveRecord::model($this->modelName)->getJSONNames($term);
			Yii::app()->end();
		}

		public function actionGetCourses($id) {
			$id = (int)$id;
			if (!Yii::app()->request->isAjaxRequest) throw new CHttpException(400);
			if (!Yii::app()->user->checkAccess('trcourse/index')) throw new CHttpException(403);
			$model = new TrIncome('clientInsert');

protected/views/client/_form_request.php
<?php echo CHtml::beginForm(array('request/index'),'post',array('id' => 'request-form', 'class' => 'form')); ?>
    <input type="hidden" name="nospam:blank" value="" />
    <input type="hidden" name="referrer" value="yourprof.ru" />
<table width="100%" height="100%">
    <tr>
        <td>
           ФИО*
        </td>
        <td>
            <input type="text" required="" name="name" id="name" />
        </td>
    </tr>
        
        <span class="error"></span>
    </label>
    
 <tr>
        <td>
           Телефон*
        </td>
        <td>
            <input type="text" required="" name="phone" id="phone" />
        </td>
    </tr>
    <tr>
        <td>
           Email*
        </td>
        <td>
            <input type="text" required="" name="email" id="email" />
        </td>
    </tr>
    <tr>
        <td>
           № Школы*
        </td>
        <td>
            <input type="text" required="" name="school" id="school" />
        </td>
    </tr>
    <tr>
        <td>
           Страничка vkontakte*
        </td>
        <td>
            <input type="text" required="" name="page" id="page11" />
        </td>
    </tr>
    <tr>
        <td>
           Выберите вариант:*:
        <input type="hidden" required="" name="colors[]" value="" />
        </td>
        
           <td>
<ul>
<li><input type="checkbox" name="colors[]" value="Русский Язык">Русский Язык</li>
<li><input type="checkbox" name="colors[]" value="Литетатура">Литетатура</li>
<li><input type="checkbox" name="colors[]" value="Математика">Математика</li>
<li><input type="checkbox" name="colors[]" value="Обществознание">Обществознание</li>
<li><input type="checkbox" name="colors[]" value="История">История</li>
<li><input type="checkbox" name="colors[]" value="Английский">Английский</li>
<li><input type="checkbox" name="colors[]" value="Биология">Биология</li>
<li><input type="checkbox" name="colors[]" value="Физика">Физика</li>
<li><input type="checkbox" name="colors[]" value="Химия">Химия</li>
</ul>
</td>
        
    </tr>
    
 
    
    <tr>
        <td>
           <input type="submit" value="Оставить заявку на курсы" name="obr1" id="request-btn"/>
        </td>
        
    </tr>
    <tr>
    
    </table>
<?php echo CHtml::endForm(); ?>

<script>
    $(document).ready(function(){
        $('#request-form').submit(function(){
            $('#request-btn').prop('value','Отправление заявки...');
            $('#request-btn').prop('disabled',true);
            $.ajax({
                async: false,
                url: '<?php echo $this->createAbsoluteUrl('request/index'); ?>',
                type: 'POST',
                data: $('#request-form').serialize()
            });
            $('#request-btn').prop('value','Отправка завершена!');
            return true;
        });
    });
</script>

protected/views/client/_index_clients.php
<style type="text/css">
    td a {
        word-wrap: break-word;
    }
</style>
<?php
    $user = Yii::app()->user->getId();
    $userModel = UserMain::model()->findByPk($user);
    $centers = [];

    if($userModel->relatedCenters){
        foreach ($userModel->relatedCenters as $center){
            $centers[$center->tr_center_id] = $center->tr_center_id;
        }
    }
    ; ?>
<div>
	<?php $this->widget('application.components.widgets.AddLinkWidget', array('htmlOptions' => array('onclick' => '$(".client-add-form").toggle(); return false;'))); ?>
</div>


<div class="hidden client-add-form">
    <?php
    if (Yii::app()->user->checkAccess('client/create')) {
        $userModel = Yii::app()->user->model;
        $managerList = UserMain::getManagerList();
        $clientModel = new Client(($managerList && ($userModel->is_partner || $userModel->is_owner)) ? 'createWithManagers' : 'createDefault');

        $this->renderPartial('_form', array('model'=>$clientModel, 'managers' => $managerList));
    }

    ?>
</div>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'client-grid',
	'template'=>'<div class="pagerControl">{summary}{pager}</div>{items}',
	'dataProvider'=>$model->search(),
	'filter' => $model,
	/* не удалять
	'afterAjaxUpdate' => 'function(){
		jQuery("#reg_date").datepicker({
			dateFormat: "d M yy",
			monthNames: '.CJSON::encode(array('Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь')).',
			monthNamesShort: '.CJSON::encode(array('янв','февр','марта','апр','мая','июня','июля','авг','сент','окт','нояб','дек')).',
			dayNames: '.CJSON::encode(array('Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота')).',
            dayNamesShort: '.CJSON::encode(array('Вс','Пн','Вт','Ср','Чт','Пт','Сб')).',
            dayNamesMin: '.CJSON::encode(array('Вс','Пн','Вт','Ср','Чт','Пт','Сб')).',
            firstDay: 1,
			changeYear: true
		});
		jQuery("#phone_num").mask(
			"+7-999-999-9999",
			{ placeholder:"*" }
		);
	}',
	*/
	'columns'=>array(
        'city_id' => array(
            'name' => 'city_id',
            'type' => 'raw',
            'value'=> 'City::nameByProjectId($data->project_id)',
            'filter'=> CHtml::activeDropDownList($model,'city_id',City::listArray(),array('empty' => 'Все города')),
            'visible'=> Yii::app()->user->model->checkRole('owner'),
        ),
        array(
            'class' => 'editable.EditableColumn',
            'name' => 'status',
            'type' => 'raw',
            'filter'=> $model->getStatusList(false),
            'headerHtmlOptions' => array('style' => 'width: 150px'),
            'editable' => array(
                'type'     => 'select',
                'url'      => $this->createUrl('ajaxUpdate'),
                'source'   => $model->getStatusList(),
				'success'  => 'function(response, newValue) {
									if(!response) {
										return "Неизвестная ошибка.";
									}

									if(response.errors) {
										 return response.errors;
									}
								}',
                'options'  => array(    //custom display
                    'display' => 'js: function(value, sourceData) {
                          var selected = $.grep(sourceData, function(o){ return value == o.value; }),
                              icons = ' . json_encode(Client::getStatusIcons()) . ';
                          $(this).html("<img style=\'height: 16px;\' src=\""+icons[value]+"\"> " + selected[0].text);
                      }'
                ),
            ),
			'value' => 'CHtml::image($data->statusIcons[$data->status], "", array("style"=>"height: 16px;")) . " " . $data->getStatusText()',
        ),
        array(
            'class' => 'editable.EditableColumn',
            'name' => 'source',
            'type' => 'raw',
            'filter' => $model->sourceList,
            'headerHtmlOptions' => array('style' => 'width: 100px'),
            'value'=> '$data->sourceText',
            'editable' => array(
                'type'     => 'select',
                'url'      => $this->createUrl('ajaxUpdate'),
                'source'   => $model->sourceList,
                'success'  => 'function(response, newValue) {
									if(!response) {
										return "Неизвестная ошибка.";
									}

									if(response.errors) {
										 return response.errors;
									}
								}'
            ),
        ),
		array(
			'name' => 'fullname',
			'type' => 'html',
			'value'=> 'CHtml::link($data->fullname,array(\'client/view\', \'id\' => $data->id))',
		),
		/* не удалять
		'reg_date' => array(
			'name' => 'reg_date',
			'type' => 'text',
			'value' => 'Yii::app()->dateFormatter->format(\'dd MMM yyyy\', $data->reg_date)',
			'filter' => $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                'model' => $model,
              	'id' => 'reg_date',
                'attribute' => 'reg_date',
                'options' => array(
                    'dateFormat' => 'd M yy',
                    'changeYear' => true
                ),
            ), true),
		),
		*/
        'phone_num' => array(
           'class' => 'editable.EditableColumn',
           'name' => 'phone_num',
           'headerHtmlOptions' => array('style' => 'width: 110px'),
           'editable' => array(    //editable section
               'url'      => $this->createUrl('ajaxUpdate'),
               'placement'  => 'right',
               'options'     => array(
                   'placeholder'=> '+7-922-333-4444',
               ),
               'validate'   => 'function(value) {
                   if (!validatePhone(value)) return "Телефона должен быть в формате +7-922-333-4444";
               }'
            ),
        ),
        'school' => array(
           'class' => 'editable.EditableColumn',
           'name' => 'school',
           'headerHtmlOptions' => array('style' => 'width: 110px'),
           'editable' => array(    //editable section
                'url'      => $this->createUrl('ajaxUpdate'),
                'placement'  => 'right',
            ),
        ),
		'course_list' => array(
			'name' => 'course_list',
			'type' => 'raw',
			'value'=> '$data->contractCourseLinks',
			'filter' => CHtml::activeDropDownList($model,'course_list',CHtml::listData(TrCourse::model()->findAll(),'id','name'),array('empty' => 'Все')),
		),
		'group_name' => array(
			'name' => 'group_name',
			'type' => 'raw',
			'value' => '$data->groupLinks',
		),
		'center__id' => array(
			'name' => 'center__id',
			'type' => 'raw',
			'value' => '$data->center->name',
			'filter' => CHtml::activeDropDownList($model,'center__id',TrCenter::model()->getCenterNamesIn(false,$centers),array('empty' => 'Все')),
		),
		'rate_one' => array(
			'name' => 'rate_one',
			'type' => 'raw',
			'value' => '$data->rate_one',
			'htmlOptions' => array('style'=>'font-size: 11px;'),
		),
		'comments_text' => array(
			'name' => 'comments_text',
			'type' => 'raw',
			'value' => '$data->commentsText',
			'htmlOptions' => array('style'=>'font-size: 11px;'),
            'filter' =>''
		),
		array(
			'class'=>'ButtonColumn',
			'template' => '{comment} {create} {delete}',
			'buttons'=>array(
				'comment' => array(
					'imageUrl' => Yii::app()->baseUrl.'/images/icon-import.png',
					'url' => 'array("client/comment", "id" => $data->id)',
			    ),
				'create' => array(
					'url' => 'array("contract/create", "id" => $data->id)',
					'label' => 'Добавить договор',
					'imageUrl' => Yii::app()->baseUrl.'/images/icon-add-contract.png',
					'visible' => '!$data->contracts',
				),
			    'update' => array(
					'url' => 'array("client/update", "id" => $data->id)',
			    ),
			    'delete' => array(
					'url' => 'array("client/delete", "id" => $data->id)',
			    ),
			),
		),
	),
));




$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
	'id'=>'commentDialog',
	'htmlOptions'=>array('style'=>'display: none;'),
	'options'=>array(
		'title'=>'Добавление комментария',
		'width'=>'470',
		'height'=>'auto',
		'autoOpen'=>false,
		'dialogClass'=> 'alert',
	),
)); ?>

	<form method="post" action="">
		<div class="row">
			<label for="ClientComments_content">Комментарий</label>
			<textarea id="ClientComments_content" name="ClientComments[content]" rows="3" cols="60"></textarea>
		</div>
		<div class="row">
			<input class="btn" type="submit" value="Добавить" name="yt0">
		</div>
	</form>
<?php
$this->endWidget('zii.widgets.jui.CJuiDialog');
?>

protected/views/client/_index_requests.php
<h2>Заявки из других источников (олимпиады, сайт, др.)</h2>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'request-grid',
	'dataProvider'=>$dataProvider,
	'columns'=>array(
        'city_id' => array(
            'type' => 'raw',
            'header' => 'Город',
            'value'=> 'City::nameByProjectId($data->project_id)',
            'visible'=> Yii::app()->user->model->checkRole('owner'),
        ),
		array(
            'class'=> 'editable.EditableColumn',
			'name' => 'fullname',
			'type' => 'raw',
			'value'=> '$data->fullname',
			'editable' => array(
				'type' => 'text',
				'url'  => $this->createUrl('ajaxUpdateRequest'),
				'validate'   => 'function(value) {
					if (!value) return "ФИО обязательны для заполнения."
				}',
                'display' => 'js: function(value, sourceData) {
					$(this).css("color",value ? "#222" : "#f00");
					$(this).html(value);
                }',
			),
			'htmlOptions' => array('class' => 'field-fullname'),
		),
		array(
            'class'=> 'editable.EditableColumn',
			'name' => 'email',
			'type' => 'raw',
			'value'=> '$data->email',
			'editable' => array(
				'type' => 'text',
				'url'  => $this->createUrl('ajaxUpdateRequest'),
				'options'     => array(
					'placeholder'=> 'mail@mail.ru',
				),
			),
			'htmlOptions' => array('class' => 'field-email'),
		),
		array(
            'class'=> 'editable.EditableColumn',
			'name' => 'source',
			'type' => 'raw',
            'filter' => Client::model()->sourceList,
			'value'=> 'Client::model()->getSourceText($data->source)',
			'editable' => array(
				'type' => 'select',
                'source'   => Client::model()->sourceList,
				'url'  => $this->createUrl('ajaxUpdateRequest'),
			),
			'htmlOptions' => array('class' => 'field-source'),
		),
		array(
            'class'=> 'editable.EditableColumn',
			'name' => 'status',
			'type' => 'raw',
            'filter' => Client::getStatusList(),
            'value'=> 'Client::model()->getStatusText($data->status)',
			'editable' => array(
				'type' => 'select',
                'source'   => Client::getStatusList(),
				'url'  => $this->createUrl('ajaxUpdateRequest'),
			),
			'htmlOptions' => array('class' => 'field-status'),
		),
		array(
            'class'=> 'editable.EditableColumn',
			'name' => 'phone_num',
			'type' => 'raw',
			'value'=> '$data->phone_num',
			'editable' => array(
				'type' => 'text',
				'url'  => $this->createUrl('ajaxUpdateRequest'),
                'options'     => array(
                   'placeholder'=> '+7-922-333-4444',
                ),
				/*
                'validate'   => 'function(value) {
                   if (!validatePhone(value)) return "Телефона должен быть в формате +7-922-333-4444";
                }',
                */
                'display' => 'js: function(value, sourceData) {
					$(this).css("color","#222");
					$(this).html(value);
                }',
			),
			'htmlOptions' => array('class' => 'field-phone'),
		),
		array(
			'name' => 'datetime',
			'type' => 'raw',
			'value' => '$data->datetime ? Yii::app()->dateFormatter->format("d MMM, HH:mm",$data->datetime) : ""',
			'htmlOptions' => array('nowrap' => true),
		),
		array(
            'class'=> 'editable.EditableColumn',
			'name' => 'school',
			'type' => 'raw',
			'value'=> '$data->school',
			'editable' => array(
				'type' => 'text',
				'url'  => $this->createUrl('ajaxUpdateRequest'),
			),
		),
		array(
            'class'=> 'editable.EditableColumn',
			'name' => 'social_vk',
			'type' => 'raw',
			'value'=> '$data->social_vk',
			'editable' => array(
				'type' => 'text',
				'url'  => $this->createUrl('ajaxUpdateRequest'),
			),
		),
		array(
            'class'=> 'editable.EditableColumn',
			'name' => 'other',
			'type' => 'raw',
			'value'=> '$data->other',
			'editable' => array(
				'type' => 'textarea',
				'url'  => $this->createUrl('ajaxUpdateRequest'),
			),
		),
		array(
			'class'=>'ButtonColumn',
			'template' => '{import} {delete}',
			'buttons'=>array(
			    'import' => array(
                    'label' => 'Импортировать в список клиентов',
                    'imageUrl' => Yii::app()->baseUrl . '/images/icon-import.png',
					'url' => 'array("client/complete", "id" => $data->id)',
					'click'=>'js: function(){
						var fullname = $(this).parent().parent().find(".field-fullname a").first().text();
						if (fullname) return true;
						alert("Необходимо заполнить ФИО.");
						return false;
					}',
			    ),
			    'delete' => array(
					'url' => 'array("client/reject", "id" => $data->id)',
			    ),
			),
		),
	),
)); ?>

protected/views/client/_profile_comments.php
<?php if ($model): ?>

<?php if (Yii::app()->user->checkAccess('client/view','comment')): ?>

<br/><br/>
<b><?php echo CHtml::encode('История взаимодействия'); ?></b><br/><br/>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'comments-grid',
    'template'=>'<div class="pagerControl">{summary}{pager}</div>{items}',
	'dataProvider'=>$model->search(),
	'filter' => $model,
	'columns'=>array(
        'datetime' => array(
            'name' => 'datetime',
            'type' => 'raw',
            'value' => '$data->datetime ? Yii::app()->dateFormatter->format("dd MMM yyyy",$data->datetime) : ""',
        ),
        'username' => array(
            'name' => 'username',
            'type' => 'raw',
            'value' => '$data->user ? CHtml::link(($data->user) ? $data->user->fullname : "Пусто",array("user/view", "id" => $data->user_id)) : ""'
        ),
        'content',
	),
)); ?>

<?php endif; ?>
<?php if (Yii::app()->user->checkAccess('client/update','addcomment')): ?>
    <div class="form">
        <?php echo CHtml::beginForm(array('client/comment', 'id' => $clientId)); ?>
        <div class="row">
            <?php echo CHtml::activeLabel($model, 'content'); ?>
            <?php echo CHtml::activeTextArea($model, 'content', array('cols' => 60, 'rows' => 3)); ?>
        </div>
        <div class="row">
            <?php echo CHtml::submitButton('Добавить', array('class' => 'btn')); ?>
        </div>
        <?php echo CHtml::endForm(); ?>
    </div>
<?php endif; ?>

<?php endif; ?>